<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Problem-Statement:" data-toc-modified-id="Problem-Statement:-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Problem Statement:</a></span><ul class="toc-item"><li><span><a href="#Dataset-Description:" data-toc-modified-id="Dataset-Description:-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Dataset Description:</a></span></li><li><span><a href="#Atribute-description" data-toc-modified-id="Atribute-description-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Atribute description</a></span></li></ul></li><li><span><a href="#Import-libraries" data-toc-modified-id="Import-libraries-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Import libraries</a></span></li><li><span><a href="#Load-data" data-toc-modified-id="Load-data-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Load data</a></span></li><li><span><a href="#Data-Understanding" data-toc-modified-id="Data-Understanding-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Data Understanding</a></span><ul class="toc-item"><li><span><a href="#Number-of-records-and-columns" data-toc-modified-id="Number-of-records-and-columns-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Number of records and columns</a></span></li><li><span><a href="#See-the-first-five-records" data-toc-modified-id="See-the-first-five-records-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>See the first five records</a></span></li><li><span><a href="#Different-classes-in-Outcome-variable" data-toc-modified-id="Different-classes-in-Outcome-variable-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Different classes in Outcome variable</a></span></li><li><span><a href="#Display-data-type-of-each-variable" data-toc-modified-id="Display-data-type-of-each-variable-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Display data type of each variable</a></span></li><li><span><a href="#Identifying-categorical-attributes" data-toc-modified-id="Identifying-categorical-attributes-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Identifying categorical attributes</a></span></li><li><span><a href="#Converting-to-appropriate-datatype" data-toc-modified-id="Converting-to-appropriate-datatype-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Converting to appropriate datatype</a></span></li><li><span><a href="#Display-data-type-of-each-variable-after-conversion" data-toc-modified-id="Display-data-type-of-each-variable-after-conversion-4.7"><span class="toc-item-num">4.7&nbsp;&nbsp;</span>Display data type of each variable after conversion</a></span></li><li><span><a href="#Dropping-ID-column-and-checking-the-length-of-columns" data-toc-modified-id="Dropping-ID-column-and-checking-the-length-of-columns-4.8"><span class="toc-item-num">4.8&nbsp;&nbsp;</span>Dropping ID column and checking the length of columns</a></span></li><li><span><a href="#Display-summary-statistics" data-toc-modified-id="Display-summary-statistics-4.9"><span class="toc-item-num">4.9&nbsp;&nbsp;</span>Display summary statistics</a></span></li><li><span><a href="#Check-the-distribution-of-all-categorical-attributes" data-toc-modified-id="Check-the-distribution-of-all-categorical-attributes-4.10"><span class="toc-item-num">4.10&nbsp;&nbsp;</span>Check the distribution of all categorical attributes</a></span></li><li><span><a href="#Checking-for-null-values" data-toc-modified-id="Checking-for-null-values-4.11"><span class="toc-item-num">4.11&nbsp;&nbsp;</span>Checking for null values</a></span></li></ul></li><li><span><a href="#Divide-the-data-into-train-and-test" data-toc-modified-id="Divide-the-data-into-train-and-test-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Divide the data into train and test</a></span></li><li><span><a href="#Preprocessing" data-toc-modified-id="Preprocessing-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Preprocessing</a></span><ul class="toc-item"><li><span><a href="#Display-all-the-columns" data-toc-modified-id="Display-all-the-columns-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Display all the columns</a></span></li><li><span><a href="#Creating-a-list-of-numerical-attributes-and-categorical-list" data-toc-modified-id="Creating-a-list-of-numerical-attributes-and-categorical-list-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Creating a list of numerical attributes and categorical list</a></span></li><li><span><a href="#LabelEncoder--:-Target-Attributes" data-toc-modified-id="LabelEncoder--:-Target-Attributes-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>LabelEncoder  : Target Attributes</a></span></li><li><span><a href="#Standard-Scaler-:-Independent-Numberic-Attributes" data-toc-modified-id="Standard-Scaler-:-Independent-Numberic-Attributes-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Standard Scaler : Independent Numberic Attributes</a></span></li><li><span><a href="#OneHotEncoder-:-Independent-Categorical-Attributes" data-toc-modified-id="OneHotEncoder-:-Independent-Categorical-Attributes-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>OneHotEncoder : Independent Categorical Attributes</a></span></li><li><span><a href="#Concatenate" data-toc-modified-id="Concatenate-6.6"><span class="toc-item-num">6.6&nbsp;&nbsp;</span>Concatenate</a></span></li></ul></li><li><span><a href="#Error-Metrics" data-toc-modified-id="Error-Metrics-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Error Metrics</a></span><ul class="toc-item"><li><span><a href="#Function-to-calculate-accuracy,-recall,-precision-and-F1-score" data-toc-modified-id="Function-to-calculate-accuracy,-recall,-precision-and-F1-score-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Function to calculate accuracy, recall, precision and F1 score</a></span></li><li><span><a href="#Function-for-Classification-Report" data-toc-modified-id="Function-for-Classification-Report-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Function for Classification Report</a></span></li></ul></li><li><span><a href="#Model-Building" data-toc-modified-id="Model-Building-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Model Building</a></span><ul class="toc-item"><li><span><a href="#Decision-Trees" data-toc-modified-id="Decision-Trees-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Decision Trees</a></span></li><li><span><a href="#Random-Forests" data-toc-modified-id="Random-Forests-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>Random Forests</a></span></li><li><span><a href="#AdaBoost" data-toc-modified-id="AdaBoost-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>AdaBoost</a></span></li><li><span><a href="#Build-Gradient-Boosting-Classifier" data-toc-modified-id="Build-Gradient-Boosting-Classifier-8.4"><span class="toc-item-num">8.4&nbsp;&nbsp;</span>Build Gradient Boosting Classifier</a></span><ul class="toc-item"><li><span><a href="#XGBOOST" data-toc-modified-id="XGBOOST-8.4.1"><span class="toc-item-num">8.4.1&nbsp;&nbsp;</span>XGBOOST</a></span><ul class="toc-item"><li><span><a href="#Create-XGBoost-Classifier" data-toc-modified-id="Create-XGBoost-Classifier-8.4.1.1"><span class="toc-item-num">8.4.1.1&nbsp;&nbsp;</span>Create XGBoost Classifier</a></span></li></ul></li><li><span><a href="#Extracting-the-important-features" data-toc-modified-id="Extracting-the-important-features-8.4.2"><span class="toc-item-num">8.4.2&nbsp;&nbsp;</span>Extracting the important features</a></span></li></ul></li><li><span><a href="#Stacking:" data-toc-modified-id="Stacking:-8.5"><span class="toc-item-num">8.5&nbsp;&nbsp;</span>Stacking:</a></span><ul class="toc-item"><li><span><a href="#References:" data-toc-modified-id="References:-8.5.1"><span class="toc-item-num">8.5.1&nbsp;&nbsp;</span>References:</a></span></li></ul></li></ul></li></ul></div>

# Problem Statement: 

Tennis Australia Open is trying to better automate how tennis points get categorized into three outcomes – 

* `Winner` – the point winning player hits a shot that is not touched by the opponent
* `Forced error` – the point winning player hits a shot that causes the opponent to not be able to return it, i.e. a good shot that is hard to handle
* `Unforced error` – the player attempting to return the ball makes an error on an otherwise normal looking rally shot

## Dataset Description:

The dataset includes point outcomes of rallies only (where the number of shots hit exceeds two, which represents the serve and return). All points were played at a past Australian Open.

## Atribute description

| Variable | Description| Value Range |
| :- | -: | :-: |
rally | The number of shots in the point counting serves and point-ending shot | An integer from 1, 2, 3...
| serve | A number indicating whether the point was played on a first or second serve.  | 1 = First, 2 = Second
| hitpoint | Shot category for point-ending shot | F = Forehand, B = Backhand, V = Volley, U = Unknown
| speed | Speed of point-ending shot | Continuous (m/s)
| net.clearance | Distance above the net as point-ending shot passed the net | Continuous (cm) distance above net. Can be negative if shot did not pass above the net.
| distance.from.sideline | Lateral distance of the point-ending shot bounce from the nearest singles sideline. | Perpendicular distance in meters (always positive even if out)
| depth | Distance of the point-ending shot bounce from the baseline | Perpendicular distance in meters
(always positive even if out)
| outside.sideline | Logical indicator of whether point-ending shot landed outside of the in-play singles sideline | TRUE, FALSE
| outside.baseline | Logical indicator of whether point-ending shot landed beyond the in-play baseline | TRUE, FALSE
| player.distance.travelled | Distance player who made the point-ending shot travelled between the impact of the penultimate shot and the impact of the point-ending shot | Euclidean distance in meters
| player.impact.depth | Distance of player who made point-ending shot from the net at the time the point-ending shot was made | Perpendicular distance along the length of court from net in meters
| player.impact.distance.from.center | Distance of player who made point-ending shot from the center line at the time the point-ending shot was made | Perpendicular distance from the center line in meters
| player.depth | Distance of player who made point-ending shot from the net at the time the penultimate shot was made | Perpendicular distance along the length of court from net in meters
| player.distance.from.center | Distance of player who made point-ending shot from the center line at the time the penultimate shot was made | Perpendicular distance from the center line in meters
| opponent.depth | Distance of opponent from the net at the time the at the time the penultimate shot was made | Perpendicular distance along the length of court from net in meters
| opponent.distance.from.center | Distance of opponent from the center line at the time the penultimate shot was made | Perpendicular distance from the center line in meters
| same.side | Logical indicator if both player and opponent were positioned on the same side of the center line (ad or deuce court) at the time the penultimate shot was made | TRUE, FALSE
| previous.speed | Speed of penultimate shot | Continuous (m/s)
| previous.net.clearance | Distance above the net as penultimate shot passed the net | Continuous (cm) distance above net. Can be negative if shot did not pass above the net.
| previous.distance.from.sideline | Lateral distance of the penultimate  shot bounce from the nearest singles sideline. | Perpendicular distance in meters (always positive even if out)
| previous.depth | Distance of the penultimate shot bounce from the baseline | Perpendicular distance in meters
(always positive even if out)
| previous.hitpoint | Shot category for penultimate shot | F = Forehand, B = Backhand, V = Volley, U = Unknown
| previous.time.to.net | Time for penultimate shot to be hit and pass the net | Continuous number in seconds
| server.is.impact.player | Logical if player who made point-ending shot was the server of the point | TRUE, FALSE
| outcome | Target variable, character with three categories indicating the type of shot that ended the point  | W (Winner), FE (Forced Error), UE (Unforced Error)
| id | A 10-character unique identifier for the point | Character

# Import libraries

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, GradientBoostingClassifier

from xgboost import XGBClassifier

from sklearn.model_selection import GridSearchCV

# Load data

In [3]:
data = pd.read_csv("tennis.csv")

# Data Understanding

In [4]:
data.drop('ID',axis=1,inplace=True)

In [5]:
y = data['outcome']
X = data.drop('outcome',axis=1)

In [6]:
num_cols = X.select_dtypes(include=['int64','float64']).columns

In [7]:
cat_cols = X.select_dtypes(include=['object','category','bool']).columns

In [8]:
X[cat_cols] = X[cat_cols].astype('category')

In [9]:
data['outcome'] = data['outcome'].astype('category')
data

rally  serve hitpoint      speed  net.clearance  distance.from.sideline  \
0         4      1        B  35.515042      -0.021725                3.474766   
1         4      2        B  33.382640       1.114202                2.540801   
2        23      1        B  22.316690      -0.254046                3.533166   
3         9      1        F  36.837309       0.766694                0.586885   
4         4      1        B  35.544208       0.116162                0.918725   
...     ...    ...      ...        ...            ...                     ...   
7996      4      2        F  36.693201       0.186101                0.457670   
7997      5      2        B  33.505322       0.985032                2.767406   
7998     10      2        F  16.906289       0.674401                0.525043   
7999      6      2        F  15.199713       0.936015                3.365840   
8000      3      1        F  30.679540      -0.033674                2.324743   

         depth  outside.sideline  outside.baseline  player.distance.travelled  \
0     6.797621             False             False                   1.467570   
1     2.608708             False              True                   2.311931   
2     9.435749             False             False                   3.903728   
3     3.342180              True             False                   0.583745   
4     5.499119             False             False                   2.333456   
...        ...               ...               ...                        ...   
7996  4.026966             False             False                   3.068317   
7997  0.275569             False              True                   3.747929   
7998  2.005257             False             False                   7.931349   
7999  1.459378             False             False                  11.454605   
8000  6.268853             False             False                   1.795455   

      ...  previous.distance.from.sideline  previous.depth  opponent.depth  \
0     ...                         2.449182        0.705435         12.5628   
1     ...                         0.583291        3.856600         12.3544   
2     ...                         1.115250        2.908892         13.8620   
3     ...                         3.256695        0.557554         14.2596   
4     ...                         1.431146        3.945317         11.3658   
...   ...                              ...             ...             ...   
7996  ...                         3.283354        3.106719         12.5438   
7997  ...                         0.422930        3.674636         13.5470   
7998  ...                         1.897760        9.208275         11.6748   
7999  ...                         0.421844        8.975572          6.9750   
8000  ...                         3.124238        2.138042         12.6112   

      opponent.distance.from.center  same.side  previous.hitpoint  \
0                            2.0724       True                  F   
1                            5.1124      False                  B   
2                            1.6564      False                  F   
3                            0.1606       True                  B   
4                            1.1082      False                  F   
...                             ...        ...                ...   
7996                         1.5368      False                  F   
7997                         0.9754      False                  F   
7998                         2.0146      False                  B   
7999                         1.2324      False                  B   
8000                         3.8698      False                  B   

      previous.time.to.net  server.is.impact.player  outcome  gender  
0                 0.445318                    False       UE    mens  
1                 0.432434                    False       FE    mens  
2                 0.397538                     True       FE    mens  
3         

In [10]:
y = data['outcome']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,stratify=y,test_size=0.3,random_state=123)

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [14]:
y_train

array([1, 2, 0, ..., 1, 1, 0])

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer


In [16]:
numeric_transformer = Pipeline(
    steps = [
        ('imputer',SimpleImputer(strategy='mean')),
        ('scaler', StandardScaler())
    ]
)

categorical_transformer = Pipeline(
    steps = [
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('onehot', OneHotEncoder(handle_unknown = 'ignore'))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, num_cols),
        ('cat', categorical_transformer, cat_cols)
    ]
)

In [48]:
RF_pipe = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', RandomForestClassifier())])

In [49]:
RF_pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['rally', 'serve', 'speed', 'net.clearance', 'distance.from.sideline',
       'depth', 'player.distance.travelled', 'player.impact.depth',
       'player.impact.distance.from.center', 'player.depth',
       'player.distance.from.c...
       'previous.time.to.net'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['hitpoint', 'outside.sideline', 'outside.baseline', 'same.side',
       'previous.hitpoint', 'server.is.impact.player', 'gender'],
      dtype='object'))])),
                ('classifier', RandomForestClassifier())])

In [36]:
from sklearn import set_config
set_config(display='diagram')

In [39]:
train_pred_RFPipe = RF_pipe.predict(X_train)
test_pred_RFPipe = RF_pipe.predict(X_test)

In [46]:
print("--Train--")
evaluate_model(y_train, train_pred_RFPipe)
print("--Test--")
evaluate_model(y_test, test_pred_RFPipe)

--Train--
Confusion Matrix 
 [[1273    0    0]
 [   0 2450    0]
 [   0    0 1877]]
Accurcay :  1.0
Recall   :  1.0
Precision:  1.0
--Test--
Confusion Matrix 
 [[386 136  23]
 [ 82 924  45]
 [ 17  23 765]]
Accurcay :  0.8642232403165347
Recall   :  0.8642232403165347
Precision:  0.8620309673249188


In [45]:
def evaluate_model(act, pred):
    from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score
    print("Confusion Matrix \n", confusion_matrix(act, pred))
    print("Accurcay : ", accuracy_score(act, pred))
    print("Recall   : ", recall_score(act, pred, average='weighted'))
    print("Precision: ", precision_score(act, pred, average='weighted'))   

In [50]:
Ada_boost_pipe = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', RandomForestClassifier())])

In [51]:
Ada_boost_pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['rally', 'serve', 'speed', 'net.clearance', 'distance.from.sideline',
       'depth', 'player.distance.travelled', 'player.impact.depth',
       'player.impact.distance.from.center', 'player.depth',
       'player.distance.from.c...
       'previous.time.to.net'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['hitpoint', 'outside.sideline', 'outside.baseline', 'same.side',
       'previous.hitpoint', 'server.is.impact.player', 'gender'],
      dtype='object'))])),
                ('classifier', RandomForestClassifier())])

In [52]:
train_pred_ada = Ada_boost_pipe.predict(X_train)
test_pred_ada = Ada_boost_pipe.predict(X_test)

In [53]:
print("--Train--")
evaluate_model(y_train, train_pred_ada)
print("--Test--")
evaluate_model(y_test, test_pred_ada)

--Train--
Confusion Matrix 
 [[1273    0    0]
 [   0 2450    0]
 [   0    0 1877]]
Accurcay :  1.0
Recall   :  1.0
Precision:  1.0
--Test--
Confusion Matrix 
 [[389 133  23]
 [ 85 922  44]
 [ 21  25 759]]
Accurcay :  0.8621407746772178
Recall   :  0.8621407746772178
Precision:  0.8601578141257935
